### PR TITLE
{WIP} 1502pt2

### PR DESCRIPTION
**Pull request by tobespc**
This backports the fix for #1502 to the 0.7.0 branch

### CODE REVIEW

**Comment by johnmcollier** [comment]
@tobespc This PR pulls in a bunch of changes unreleated to https://github.com/eclipse/codewind-installer/pull/294, was that intended?

**Comment by jopit** [comment]
I think this change may cause problems during migration.

**Comment by jopit** [comment]
When I start the codewind containers using the 0.6.0 version of cwctl, and then use the version of cwctl from master (which includes this master version of this change), `./cwctl status` reports the containers are not running, even though they are.  This because of the the new code looks for images tagged with the `eclipse/` prefix, while 0.6.0 starts images without the `eclipse/` prefix.

I'm not sure what effect this will have during the actual move from 0.6.x to 0.7.0

```
✔ ~/codewind/cli6/darwin 
% ./cwctl start -t latest
Debug: false
Stopping Codewind and Project containers
Removing Codewind docker networks..
==> created file codewind-docker-compose.yaml
==> environment structure written to codewind-docker-compose.yaml
System architecture is:  amd64
Host operating system is:  darwin
Attempting to find available port
Port 10000 Available
Please wait whilst containers initialize...  
Creating network "codewind_network" with the default driver
Creating codewind-performance ... done
Creating codewind-pfe         ... done
Waiting for Codewind to start
.
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000

✔ ~/codewind/cli6/darwin 
% docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
a91e750bf045        cw-gogo-5adf1380-2021-11ea-8b2c-356ccde9b167   "/app/main"              7 seconds ago       Up 5 seconds        127.0.0.1:32875->8000/tcp   cw-gogo-5adf1380-2021-11ea-8b2c-356ccde9b167
20f68db6c949        codewind-pfe-amd64:latest                      "sh -c ' /file-watch…"   10 seconds ago      Up 8 seconds        127.0.0.1:10000->9090/tcp   codewind-pfe
f41e86bc5dc1        codewind-performance-amd64:latest              "docker-entrypoint.s…"   11 seconds ago      Up 9 seconds        127.0.0.1:9095->9095/tcp    codewind-performance

✔ ~/codewind/cli6/darwin 
% cd ../../cli/darwin 

✔ ~/codewind/cli/darwin 
% ./cwctl status
Codewind is installed but not running
```

**Comment by jopit** [comment]
Deleted some comments because they were wrong.

**Comment by jopit** [comment]
I was wrong about being wrong.  It looks like this change will break migration if the older version of codewind is already running.

I installed and started codewind 0.6.1, then in my 0.7.0 version of vscode, I replaced the cwctl binary with the one from master (which already has this change).

Note that cwctl and therefore the IDEs think that codewind is not running when in fact it is, because the new cwctl is looking for container's whose names start with `eclipse/`. 

When I tried to migrate, I got an error, possibly because there is no docker-compose file in the ~/.codewind folder.

```
cwctl is available at /Users/jsp/.codewind/0.7.0/cwctl
==> Run cwctl --json --insecure connections list
{"schemaversion":1,"connections":[{"id":"local","label":"Codewind local connection","url":"","auth":"","realm":"","clientid":"","username":""}]}
==> End cwctl --json --insecure connections list
==> Run cwctl --json --insecure status
{"status":"stopped","installed-versions":["0.6.1"]}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"stopped","installed-versions":["0.6.1"]}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"stopped","installed-versions":["0.6.1"]}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"stopped","installed-versions":["0.6.1"]}
==> End cwctl --json --insecure status
==> Run cwctl --json remove -t 0.6.1
Removing Codewind docker images..
System architecture is:  amd64
Host operating system is:  darwin
Please wait whilst images are removed...  
2019/12/16 16:17:43 DOCKER_COMPOSE_ERROR[101]: exit status 1. docker-compose remove command failed to execute correctly
==> End cwctl --json remove -t 0.6.1
```

**Comment by tobespc** [comment]
closing and doing it again

**Pull request closed without merging**
