### PR TITLE
{WIP DO NOT MERGE} test for James

### PR DESCRIPTION
**Pull request by tobespc**
Signed-off-by: Toby Corbin <corbint@uk.ibm.com>

### CODE REVIEW

**Comment by liamchampton** [comment]
Upgrading to `golang:1.12-stretch` has been successful (can be seen in this PR). We should to discuss the best place to store the cache dir/removal of it as this PR will store it in the current working directory. @tobespc This can be closed and I will open a new PR for this work on a better branch name etc.

**Comment by liamchampton** [comment]
Update - This is now working with a clean up of the cache directory after the build/execution of code

**Comment by stalleyj** [comment]
No longer required.

**Comment by tobespc** [comment]
re opening for @james-wallis

**Comment by hhellyer** [comment]
Closing as requested.

**Pull request closed without merging**
