### PR TITLE
Feature/better kubeconfig resolving

### PR DESCRIPTION
**Pull request by bsteinfeld**
## What type of PR is this ? 

- [ ] Bug fix
- [x] Enhancement

## What does this PR do ?

Resolve Kubernetes config with the follow precedence:

1. Check for config under $KUBECONFIG
2. Check for config under $HOME/.kube/config
3. Use the 'In-cluster config' if present.

## Which issue(s) does this PR fix ?

https://github.com/eclipse/codewind/issues/2051

## Does this PR require a documentation change ?

Not required, but it would be nice (especially for IKS which generally recommends exporting `KUBECONFIG`)

## Any special notes for your reviewer ?

This PR is still a WIP. I would like advice regarding:

• Best practises for writing/modifying code (e.g. code styling, or do I need to update the CLI's help text)
• Should I apply this fix to other [remote] operations (e.g. https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/remove.go#L207-L209)

### CODE REVIEW

**Comment by johnmcollier** [comment]
@bsteinfeld Thanks for your changes, they look good to me from a quick overview, can you amend all of your previous commits to add: `Signed off by: <email>` in the footer? 

Also, it looks like Eclipse doesn't like the email you used, can you make sure that's the email you used to sign the ECA?

(It might be easier to rebase into a single commit and force push)

**Comment by bsteinfeld** [comment]
> @bsteinfeld Thanks for your changes, they look good to me from a quick overview, can you amend all of your previous commits to add: `Signed off by: <email>` in the footer?
> 
> Also, it looks like Eclipse doesn't like the email you used, can you make sure that's the email you used to sign the ECA?
> 
> (It might be easier to rebase into a single commit and force push)

I just swashed my commits and added:

```
Signed-off-by: Bradley Steinfeld <bs@ibm.com>
```

 to the commit message

**Comment by johnmcollier** [comment]
ECA check now happy 👍

**Comment by johnmcollier** [comment]
@markcor11 Can you review too since you're most familiar with the CLI remote code?

**Comment by hhellyer** [comment]
Reading the docs for IKS it looks like they are changing how they handle `$KUBECONFIG` a bit too:
https://cloud.ibm.com/docs/containers-cli-plugin?topic=containers-cli-plugin-kubernetes-service-cli#cs_beta (search for 'Appends the new kubeconfig')
and might of missed it was supposed to be a list originally.

**Comment by bsteinfeld** [comment]
@hhellyer Made changes to handle empty `KUBECONFIG` and multiple paths (choose first as per: https://cloud.ibm.com/docs/containers-cli-plugin?topic=containers-cli-plugin-kubernetes-service-cli#cs_beta)

I don't know how to get around this ECA thing though.... I added the `Signed-off-by` to `525d6a3` but it's still failing.

**Comment by johnmcollier** [comment]
@bsteinfeld The ECA check is failing because not every commit contains the `Signed-off-by` footer. 

It's probably easier to just squash the commits into one and add the footer to the resultant commit.

**Comment by bsteinfeld** [comment]
Closed as replaced by: https://github.com/eclipse/codewind-installer/pull/401

**Pull request closed without merging**
