### PR TITLE
Change mustgather command name to diagnostics

### PR DESCRIPTION
**Pull request by mattcolegate**
Signed-off-by: Matthew Colegate <colegate@uk.ibm.com>

## What type of PR is this ? 

- [ ] Bug fix
- [X] Enhancement

## What does this PR do ?
Simple name change - `cwctl mustgather` becomes `cwctl diagnostics`

## Which issue(s) does this PR fix ?
https://github.com/eclipse/codewind/issues/2766
#### Link to the [Codewind repository](https://github.com/eclipse/codewind/issues) issue(s) this PR fixes or references:
https://github.com/eclipse/codewind/issues/2766
## Does this PR require a documentation change ?
Yes

### CODE REVIEW

**Comment by mattcolegate** [comment]
WIP because there's still a poll available to decide the name

**Comment by jcockbain** [comment]
These changes themselves looks fine - is the plan to also change the name of `actions/mustgather.go` and all the references to `mustgather` in there?

**Comment by mattcolegate** [comment]
I mean, I _could_ change them... programatically it won't make a difference... how much do you think it'll bother people?

**Comment by jcockbain** [comment]
I think it would make more sense to call the file `diagnostics.go` or similar. As it stays in the same package it should still work after just changing the filename. 

The directory that's written to is also still `~/codewind/mustgather` too, which might also be confusing?

**Comment by mattcolegate** [comment]
Great point about the directory being mustgather! Yes, that would be confusing. I'll make the changes.

**Comment by mattcolegate** [comment]
@jcockbain OK, changes are made - please re-review at your earliest convenience

**Comment by jcockbain** [comment]
Thanks for making those changes, pulled and ran the command and all worked fine for me.

**Pull request merged**
