### PR TITLE
add pull request template

### PR DESCRIPTION
**Pull request by liamchampton**
**Problem**
We do not have any templates on this repository

**Solution**
Create a comprehensive yet simple pull request template to help guide people when submitting code to help eliminate simple errors

Followed the community guide https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

Signed-off-by: Liam Hampton <liam.hampton@ibm.com>

### CODE REVIEW

**Comment by jcockbain** [comment]
LGTM

**Comment by hhellyer** [comment]
I'm not sure if this is right for the template but our git commits should follow this standard:
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record
Since that's on every commit to git - not PR - it effectively implies all PR's should be squashed to a single commit before merging.
We should also have the same rules project wide.

**Comment by hhellyer** [comment]
I'd definitely like to see a reference to the ECA. I'm not sure if it needs a checkbox because the automation will verify it but having it there to remind the person creating the PR would be good.
I'd also like to see a reference to the Eclipse commit record guidelines, so we start following them!

**Comment by liamchampton** [comment]
> I'd definitely like to see a reference to the ECA. I'm not sure if it needs a checkbox because the automation will verify it but having it there to remind the person creating the PR would be good.
> I'd also like to see a reference to the Eclipse commit record guidelines, so we start following them!

Certainly agree. I will amend the PR.

**Pull request merged**
